# Generated by Django 4.1.7 on 2023-04-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image1',
            new_name='imagebw1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image2',
            new_name='imageclr2',
        ),
    ]
