# Generated by Django 4.1.7 on 2023-04-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_products_image3_products_image4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
